angular.module('Config', ['ngRoute'])
.config(function ($routeProvider, $locationProvider) {
    $routeProvider.when('/CheckOut', {
        templateUrl: '/Templates/Order',
        controller: 'OrderCtrl'
    }).when('/404', {
        templateUrl: '/Templates/Error',
        controller: 'NotFound'
    }).when('/Return', {
        templateUrl: '/Templates/Return',
        controller: 'ReturnCtrl'
    }).when('/TakeOut', {
        templateUrl: '/Templates/TakeOut',
        controller: 'TakeOutCtrl'
    }).when('/Conbine', {
        templateUrl: '/Templates/Conbine',
        controller: 'ConbineCtrl'
    }).when('/Replace', {
        templateUrl: '/Templates/Replace',
        controller: 'ReplaceCtrl'
    }).when('/HandOut', {
        templateUrl: '/Templates/HandOut',
        controller: 'HandOutCtrl'
    }).when('/Areas', {
        templateUrl: '/Baseinfo/Areas',
        controller: 'AreasCtrl'
    }).when('/Desks', {
        templateUrl: '/Baseinfo/Desks',
        controller: 'DesksCtrl'
    }).when('/Menus', {
        templateUrl: '/Baseinfo/Menus',
        controller: 'MenusCtrl'
    }).when('/paykinds', {
        templateUrl: '/PayKinds/Index',
        controller: 'PayKindsCtrl'
    }).when('/MenuClass', {
        templateUrl: '/Baseinfo/MenuClasses',
        controller: 'MenuClassesCtrl'
    }).when('/printers', {
        templateUrl: '/Printers/Index',
        controller: 'PrintersCtrl'
    }).when('/StaffRoles', {
        templateUrl: '/Baseinfo/StaffRoles',
        controller: 'StaffRolesCtrl'
    }).when('/Staffs', {
        templateUrl: '/Baseinfo/Staffs',
        controller: 'StaffCtrl'
    }).when('/timediscounts', {
        templateUrl: '/TimeDiscounts/Index',
        controller: 'TimeDiscountsCtrl'
    }).when('/hotels', {
        templateUrl: '/Hotels/Index',
        controller: 'HotelsCtrl'
    }).when('/MenuRemarks', {
        templateUrl: '/Baseinfo/MenuRemarks',
        controller: 'MenuRemarksCtrl'
    }).when('/Department', {
        templateUrl: '/Baseinfo/Department',
        controller: 'DepartmentCtrl'
    }).when('/vip', {
        templateUrl: '/Vip/Index',
        controller: 'VipCtrl'
    }).when('/MenuSales', {
        templateUrl: '/Reports/MenuSales',
        controller: 'MenuSalesCtrl'
    }).when('/DailyOrder', {
        templateUrl: '/DinePaidDetails/Index',
        controller: 'DinePaidDetailsCtrl'
    }).when('/PaykindType', {
        templateUrl: '/Reports/PayTotal',
        controller: 'PaykindTypeCtrl'
    }).when('/MenuSaleClass', {
        templateUrl: '/Reports/MenuSaleclass',
        controller: 'MenuSaleClassCtrl'
    }).when('/MenuSalesClass', {
        templateUrl: '/Reports/SaleClass',
        controller: 'MenuSalesClassCtrl'
    }).when('/SetMeals', {
        templateUrl: '/Baseinfo/SetMeals',
        controller: 'SetMealsCtrl'
    }).when('/menusetmeals', {
        templateUrl: '/MenuSetMeals/Index',
        controller: 'MenuSetMealsCtrl'
    }).when('/menuonsales', {
        templateUrl: '/MenuOnSales/Index',
        controller: 'MenuOnSalesCtrl'
    }).when('/menusetmeals', {
        templateUrl: '/MenuSetMeals/Index',
        controller: 'MenuSetMealsCtrl'
    }).when('/dailysales', {
        templateUrl: '/DailySales/Index',
        controller: 'DailySalesCtrl'
    }).when('/monthSales', {
        templateUrl: '/Reports/monthSales',
        controller: 'monthSalesCtrl'
    }).when('/soldout', {
        templateUrl: '/SoldOut/Index',
        controller: 'SoldOutCtrl'
    }).when('/YearSale', {
        templateUrl: '/Reports/Years',
        controller: 'YearSaleCtrl'
    }).when('/SaleRange', {
        templateUrl: '/Reports/SaleRange',
        controller: 'SaleRangeCtrl'
    }).when('/SalesAll', {
        templateUrl: '/Reports/SalesAll',
        controller: 'SalesAllCtrl'
    }).when('/paydetails', {
        templateUrl: '/PayDetails/Index',
        controller: 'PayDetailsCtrl'
    }).when('/AddMenu', {
        templateUrl: '/Templates/AddMenu',
        controller: 'AddMenuCtrl'
    }).when('/Reasons', {
        templateUrl: '/Baseinfo/Reason',
        controller: 'ReturnCtrl'
    }).when('/Printer', {
        templateUrl: '/Baseinfo/Printer',
        controller: 'PrinterCtrl'
    }).when('/ReSoldOut', {
        templateUrl: '/Baseinfo/ReSoldOut',
        controller: 'SoldOutCtrl'
    }).when('/RePrinter', {
        templateUrl: '/Templates/RePrinter',
        controller: 'RePrinterCtrl'
    }).when('/PayAll', {
        templateUrl: '/Templates/PayAll',
        controller: 'PayAllCtrl'
    }).when('/Invoice', {
        templateUrl: '/Reports/Invoice',
        controller: 'InvoiceCtrl'
    }).when('/DailyDetail', {
        templateUrl: '/Templates/DailyDetail',
        controller: 'DailyDetailCtrl'
    }).otherwise({
        redirectTo: '/404'
    });
})